name: My First Workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

  schedule:
    - cron: '0 9 * * *'

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: node node_modules/playwright/cli.js install --with-deps

      - name: Run JavaScript file
        run: node index.js

      - name: Run Playwright tests
        run: node node_modules/playwright/cli.js test