name: My First Workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

  schedule:
    - cron: '0 9 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: github-actions-practice
      ENVIRONMENT: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: |
          echo "Building $APP_NAME"
          echo "Environment: $ENVIRONMENT"
          echo "Build completed successfully"


  test:
    runs-on: ubuntu-latest
    needs: build

    env:
      APP_NAME: github-actions-practice
      ENVIRONMENT: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: node node_modules/playwright/cli.js install --with-deps

      - name: Run Playwright tests
        run: node node_modules/playwright/cli.js test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/


  deploy:
    runs-on: ubuntu-latest
    needs: test

    env:
      APP_NAME: github-actions-practice
      ENVIRONMENT: staging

    steps:
      - name: Deploy application
        run: |
          echo "Deploying $APP_NAME"
          echo "Environment: $ENVIRONMENT"
          echo "Deployment completed successfully"